configured_endpoints: 2
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/landingai%2Fade-e12bfbad2338073891016dee51efcca01e2339f0502cd1bcef085bb1dad182c6.yml
openapi_spec_hash: 8c479ef363b165ee959a3ee9c7e3aeed
config_hash: 0bc3c0a77bcf7ab5dbdfd5ec623243f3
