/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/ade/classify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Classify
         * @description Classify the pages of a document into classes you define.
         *
         *     This endpoint accepts PDFs, images, and other supported file types
         *     (either as a `document` upload or `document_url`) together with a
         *     list of `classes`, and returns a classification result for each page.
         *
         *     For EU users, use this endpoint:
         *
         *     `https://api.va.eu-west-1.landing.ai/v1/ade/classify`.
         */
        post: operations["tool_ade_classify_v1_ade_classify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Extract
         * @description Extract structured data from Markdown using a JSON schema.
         *
         *     This endpoint
         *         processes Markdown content and extracts structured data according to the provided
         *         JSON schema.
         *
         *     For EU users, use this endpoint:
         *
         *
         *         `https://api.va.eu-west-1.landing.ai/v1/ade/extract`.
         */
        post: operations["tool_ade_extract_v1_ade_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/extract/build-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Build Extract Schema
         * @description Generate a JSON schema from Markdown using AI.
         *
         *     This endpoint analyzes Markdown
         *         content and generates a JSON schema suitable for use with the extract endpoint.
         *         It can also refine an existing schema based on new documents or iterate on a schema
         *         based on prompt instructions.
         *
         *     For EU users, use this endpoint:
         *
         *
         *         `https://api.va.eu-west-1.landing.ai/v1/ade/extract/build-schema`.
         */
        post: operations["tool_ade_build_schema_v1_ade_extract_build_schema_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/extract/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE List Extract Jobs
         * @description List all async extract jobs associated with your API key.
         *
         *     Returns the list of jobs or an error response. For EU users, use this endpoint:
         *
         *     `https://api.va.eu-west-1.landing.ai/v1/ade/extract/jobs`.
         */
        get: operations["tool_ade_list_extract_jobs_v1_ade_extract_jobs_get"];
        put?: never;
        /**
         * ADE Extract Jobs
         * @description Extract structured data asynchronously.
         *
         *     This endpoint creates a job that handles the processing for large markdown
         *     documents.
         *
         *     For EU users, use this endpoint:
         *
         *     `https://api.va.eu-west-1.landing.ai/v1/ade/extract/jobs`.
         */
        post: operations["tool_ade_extract_jobs_v1_ade_extract_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/extract/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE Get Extract Jobs
         * @description Get the status for an async extract job.
         *
         *     Returns the job status or an error
         *        response. For EU users, use this endpoint:
         *
         *
         *        `https://api.va.eu-west-1.landing.ai/v1/ade/extract/jobs/{job_id}`.
         */
        get: operations["tool_ade_get_extract_jobs_v1_ade_extract_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Parse
         * @description Parse a document or spreadsheet.
         *
         *     This endpoint parses documents (PDF, images)
         *         and spreadsheets (XLSX, CSV) into structured Markdown, chunks, and metadata.
         *
         *
         *      For EU users, use this endpoint:
         *
         *
         *         `https://api.va.eu-west-1.landing.ai/v1/ade/parse`.
         */
        post: operations["tool_ade_parse_v1_ade_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/parse/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE List Parse Jobs
         * @description List all async parse jobs associated with your API key. Returns the list of jobs
         *     or an error response. For EU users, use this endpoint:
         *
         *
         *     `https://api.va.eu-west-1.landing.ai/v1/ade/parse/jobs`.
         */
        get: operations["tool_ade_list_parse_jobs_v1_ade_parse_jobs_get"];
        put?: never;
        /**
         * ADE Parse Jobs
         * @description Parse documents asynchronously.
         *
         *     This endpoint creates a job that handles the
         *         processing for both large documents and large batches of documents.
         *
         *      For EU
         *         users, use this endpoint:
         *
         *
         *         `https://api.va.eu-west-1.landing.ai/v1/ade/parse/jobs`.
         */
        post: operations["tool_ade_parse_jobs_v1_ade_parse_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/parse/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE Get Parse Jobs
         * @description Get the status for an async parse job.
         *
         *     Returns the job status or an error
         *        response. For EU users, use this endpoint:
         *
         *
         *        `https://api.va.eu-west-1.landing.ai/v1/ade/parse/jobs/{job_id}`.
         */
        get: operations["tool_ade_get_parse_jobs_v1_ade_parse_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/section": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Section
         * @description Section parsed markdown into a hierarchical table of contents.
         *
         *     This endpoint accepts the markdown output from /ade/parse
         *     (with reference anchors) and returns a flat, reading-order list of
         *     sections with hierarchy levels and reference ranges.
         *
         *     For EU users, use this endpoint:
         *
         *     `https://api.va.eu-west-1.landing.ai/v1/ade/section`.
         */
        post: operations["tool_ade_section_v1_ade_section_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ade/split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Split
         * @description Split classification for documents.
         *
         *     This endpoint classifies document sections
         *         based on markdown content and split options.
         *
         *     For EU users, use this endpoint:
         *
         *
         *         `https://api.va.eu-west-1.landing.ai/v1/ade/split`.
         */
        post: operations["tool_ade_split_v1_ade_split_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AsyncExtractRequest
         * @description Request model for async extract endpoint.
         *
         *     Extends ExtractRequest with output_save_url for ZDR support.
         */
        AsyncExtractRequest: {
            /**
             * Markdown
             * @description The Markdown file or Markdown content to extract data from.
             */
            markdown?: string | null;
            /**
             * Markdown Url
             * @description The URL to the Markdown file to extract data from.
             */
            markdown_url?: string | null;
            /**
             * Model
             * @description The version of the model to use for extraction. Use `extract-latest` to use the latest version.
             */
            model?: string | null;
            /**
             * Output Save Url
             * @description If zero data retention (ZDR) is enabled, you must enter a URL for the extracted output to be saved to. When ZDR is enabled, the extracted content will not be in the API response.
             */
            output_save_url?: string | null;
            /**
             * Schema
             * @description JSON schema for field extraction. This schema determines what key-values pairs are extracted from the Markdown. The schema must be a valid JSON object and will be validated before processing the document.
             */
            schema: string;
            /**
             * Strict
             * @description If True, reject schemas with unsupported fields (HTTP 422). If False, prune unsupported fields and continue. Only applies to extract versions that support schema validation.
             * @default false
             */
            strict: boolean;
        };
        /** AsyncParseRequestWithEncryptedPassword */
        AsyncParseRequestWithEncryptedPassword: {
            /**
             * Custom Prompts
             * @description Optional JSON string mapping chunk types to custom parsing prompts. Only the `figure` key is supported, for example '{"figure":"Describe axis labels in detail."}'.
             */
            custom_prompts?: string | null;
            /**
             * Document
             * @description A file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document_url` parameter must be provided.
             */
            document?: string | null;
            /**
             * Document Url
             * @description The URL to the file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document` parameter must be provided.
             */
            document_url?: string | null;
            /**
             * Model
             * @description The version of the model to use for parsing.
             */
            model?: string | null;
            /**
             * Output Save Url
             * @description If zero data retention (ZDR) is enabled, you must enter a URL for the parsed output to be saved to. When ZDR is enabled, the parsed content will not be in the API response.
             */
            output_save_url?: string | null;
            /**
             * Password
             * @description Password for encrypted document files. If the document is password-protected, provide the password to decrypt and process the document. Ignored for unencrypted documents.
             */
            password?: string | null;
            /** @description If you want to split documents into smaller sections, include the split parameter. Set the parameter to page to split documents at the page level. The splits object in the API output will contain a set of data for each page. */
            split?: components["schemas"]["SplitType"] | null;
        };
        /** BuildSchemaMetadata */
        BuildSchemaMetadata: {
            /**
             * Credit Usage
             * @default 0
             */
            credit_usage: number;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Filename */
            filename?: string | null;
            /**
             * Job Id
             * @default
             */
            job_id: string;
            /** Org Id */
            org_id?: string | null;
            /** Version */
            version?: string | null;
            /**
             * Warnings
             * @description Structured warnings from the extraction process. Each warning is an instance of ExtractWarning with 'code' (e.g. 'nonconformant_schema') and 'msg' (human-readable description). Present only for extract versions from extract-20260314 and above that support structured warnings.
             */
            warnings?: components["schemas"]["ExtractWarning"][];
        };
        /** BuildSchemaRequest */
        BuildSchemaRequest: {
            /**
             * Markdown Urls
             * @description URLs to Markdown files to analyze for schema generation.
             */
            markdown_urls?: string[] | null;
            /**
             * Markdowns
             * @description Markdown files or inline content strings to analyze for schema generation. Multiple documents can be provided for better schema coverage.
             */
            markdowns?: (string)[] | null;
            /**
             * Model
             * @description The version of the model to use for schema generation. Use `extract-latest` to use the latest version.
             */
            model?: string | null;
            /**
             * Prompt
             * @description Instructions for how to generate or modify the schema.
             */
            prompt?: string | null;
            /**
             * Schema
             * @description Existing JSON schema to iterate on or refine.
             */
            schema?: string | null;
        };
        /** BuildSchemaResponse */
        BuildSchemaResponse: {
            /**
             * Extraction Schema
             * @description The generated JSON schema as a string.
             */
            extraction_schema: string;
            /** @description The metadata for the schema generation process. */
            metadata: components["schemas"]["BuildSchemaMetadata"];
        };
        /**
         * ClassificationItem
         * @description A single page-level classification result.
         */
        ClassificationItem: {
            /**
             * Class
             * @description Predicted class label or 'unknown'.
             */
            class: string;
            /**
             * Page
             * @description Page number (0-based).
             */
            page: number;
            /**
             * Reason
             * @description Reason for the classification (for debugging).
             * @default
             */
            reason: string;
            /**
             * Suggested Class
             * @description Proposed class when the prediction is 'unknown'.
             */
            suggested_class?: string | null;
        };
        /**
         * ClassifyClass
         * @description A single classification option: a class name plus optional description.
         */
        ClassifyClass: {
            /**
             * Class
             * @description Name of the class.
             */
            class: string;
            /**
             * Description
             * @description Detailed description of what this class represents.
             */
            description?: string | null;
        };
        /**
         * ClassifyMetadata
         * @description Metadata for the classify response.
         */
        ClassifyMetadata: {
            /** Credit Usage */
            credit_usage: number;
            /** Duration Ms */
            duration_ms: number;
            /** Filename */
            filename: string;
            /**
             * Job Id
             * @default
             */
            job_id: string;
            /** Org Id */
            org_id?: string | null;
            /** Page Count */
            page_count: number;
            /** Version */
            version?: string | null;
        };
        /** ClassifyRequest */
        ClassifyRequest: {
            /**
             * Classes
             * @description The possible classes that can be assigned to pages in the document. Each entry is an object with a `class` name and an optional `description`. Only one class is assigned per page; unclassifiable pages receive 'unknown'. Can be provided as a JSON string in form data.
             */
            classes: components["schemas"]["ClassifyClass"][];
            /**
             * Document
             * @description A file to be classified. Either this parameter or the `document_url` parameter must be provided.
             */
            document?: string | null;
            /**
             * Document Url
             * @description The URL of the document to be classified. Either this parameter or the `document` parameter must be provided.
             */
            document_url?: string | null;
            /**
             * Model
             * @description Classification model version. Defaults to the latest.
             */
            model?: string | null;
        };
        /**
         * ClassifyResponse
         * @description Response model for the classify endpoint.
         */
        ClassifyResponse: {
            /** Classification */
            classification: components["schemas"]["ClassificationItem"][];
            metadata: components["schemas"]["ClassifyMetadata"];
        };
        /**
         * CustomPromptKey
         * @description Chunk types that support custom prompts.
         * @constant
         * @enum {string}
         */
        CustomPromptKey: "figure";
        /**
         * CustomPrompts
         * @description Map of chunk type to custom prompt string.
         */
        CustomPrompts: {
            [key: string]: string;
        };
        /**
         * ExtractJobStatusResponse
         * @description The status of an extract job, plus the results once it completes.
         */
        ExtractJobStatusResponse: {
            /**
             * Created At
             * @description Unix timestamp (in seconds) for when the job was created.
             * @default 0
             */
            created_at: number;
            /** @description The extraction results, returned here when the job is complete and you did not set an `output_save_url`. Large results are returned through `output_url` instead. */
            data?: components["schemas"]["ExtractResponse"] | null;
            /**
             * Failure Reason
             * @description If the job failed, a message describing what went wrong.
             */
            failure_reason?: string | null;
            /**
             * Job Id
             * @description A unique identifier for this extract job.
             */
            job_id: string;
            /** @description Information about the extraction, such as the model version, duration, credit usage, and any schema warnings. */
            metadata?: components["schemas"]["ExtractMetadata"] | null;
            /**
             * Org Id
             * @description Organization ID.
             */
            org_id?: string | null;
            /**
             * Output Url
             * @description A URL to download the extraction results. Provided when the job is complete and either you set an `output_save_url` or the result is larger than 1 MB. URLs for large results are temporary and expire one hour after you request the job.
             */
            output_url?: string | null;
            /**
             * Progress
             * @description Job completion. Either 0.0 (not yet complete) or 1.0 (complete).
             */
            progress: number;
            /**
             * Received At
             * @description Unix timestamp (in seconds) for when the job was received.
             */
            received_at: number;
            /**
             * Status
             * @description The current state of the job: `pending`, `processing`, `completed`, `failed`, or `cancelled`.
             */
            status: string;
            /**
             * Version
             * @description The exact model snapshot used for the extraction.
             */
            version?: string | null;
        };
        /** ExtractMetadata */
        ExtractMetadata: {
            /** Credit Usage */
            credit_usage: number;
            /** Duration Ms */
            duration_ms: number;
            /**
             * Fallback Model Version
             * @description The extract model that was actually used to extract the data when the initial extraction attempt failed with the requested version.
             */
            fallback_model_version?: string | null;
            /** Filename */
            filename: string;
            /** Job Id */
            job_id: string;
            /** Org Id */
            org_id: string | null;
            /**
             * Schema Violation Error
             * @description A detailed error message shows why the extracted data does not fully conform to the input schema. Null means the extraction result is consistent with the input schema.
             */
            schema_violation_error?: string | null;
            /** Version */
            version: string | null;
            /**
             * Warnings
             * @description Structured warnings from the extraction process. Each warning is an instance of ExtractWarning with 'code' (e.g. 'nonconformant_schema') and 'msg' (human-readable description). Present only for extract versions from extract-20260314 and above that support structured warnings.
             */
            warnings?: components["schemas"]["ExtractWarning"][];
        };
        /** ExtractRequest */
        ExtractRequest: {
            /**
             * Markdown
             * @description The Markdown file or Markdown content to extract data from.
             */
            markdown?: string | null;
            /**
             * Markdown Url
             * @description The URL to the Markdown file to extract data from.
             */
            markdown_url?: string | null;
            /**
             * Model
             * @description The version of the model to use for extraction. Use `extract-latest` to use the latest version.
             */
            model?: string | null;
            /**
             * Schema
             * @description JSON schema for field extraction. This schema determines what key-values pairs are extracted from the Markdown. The schema must be a valid JSON object and will be validated before processing the document.
             */
            schema: string;
            /**
             * Strict
             * @description If True, reject schemas with unsupported fields (HTTP 422). If False, prune unsupported fields and continue. Only applies to extract versions that support schema validation.
             * @default false
             */
            strict: boolean;
        };
        /** ExtractResponse */
        ExtractResponse: {
            /**
             * Extraction
             * @description The extracted key-value pairs.
             */
            extraction: Record<string, never>;
            /**
             * Extraction Metadata
             * @description The extracted key-value pairs and the chunk_reference for each one.
             */
            extraction_metadata: Record<string, never>;
            /** @description The metadata for the extraction process. */
            metadata: components["schemas"]["ExtractMetadata"];
        };
        /** ExtractWarning */
        ExtractWarning: {
            /** @description The type of warning, used to translate to a status code downstream */
            code: components["schemas"]["ExtractWarningCode"];
            /**
             * Msg
             * @description Human-readable description of the warning with more details
             */
            msg: string;
        };
        /**
         * ExtractWarningCode
         * @enum {string}
         */
        ExtractWarningCode: "nonconformant_schema" | "nonconformant_output";
        /**
         * GroundingType
         * @enum {string}
         */
        GroundingType: "chunkLogo" | "chunkCard" | "chunkAttestation" | "chunkScanCode" | "chunkForm" | "chunkTable" | "chunkFigure" | "chunkText" | "chunkMarginalia" | "chunkTitle" | "chunkPageHeader" | "chunkPageFooter" | "chunkPageNumber" | "chunkKeyValue" | "table" | "tableCell";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobCreationResponse */
        JobCreationResponse: {
            /** Job Id */
            job_id: string;
        };
        /**
         * JobStatusResponse
         * @description Unified response for job status endpoint.
         */
        JobStatusResponse: {
            /**
             * Created At
             * @description Unix timestamp (seconds) for when the job was created. Mirrors received_at; exposed so clients have an explicit creation time.
             * @default 0
             */
            created_at: number;
            /**
             * Data
             * @description The parsed output (ParseResponse for documents, SpreadsheetParseResponse for spreadsheets), if the job is complete and the `output_save_url` parameter was not used.
             */
            data?: components["schemas"]["ParseResponse"] | components["schemas"]["SpreadsheetParseResponse"] | null;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Job Id */
            job_id: string;
            metadata?: components["schemas"]["ParseMetadata"] | null;
            /** Org Id */
            org_id?: string | null;
            /**
             * Output Url
             * @description The URL to the parsed content. This field contains a URL when the job is complete and either you specified the `output_save_url` parameter or the result is larger than 1MB. When the result exceeds 1MB, the URL is a presigned S3 URL that expires after 1 hour. Each time you GET the job, a new presigned URL is generated.
             */
            output_url?: string | null;
            /**
             * Progress
             * @description Job completion progress as a decimal from 0 to 1, where 0 is not started, 1 is finished, and values between 0 and 1 indicate work in progress.
             */
            progress: number;
            /** Received At */
            received_at: number;
            /** Status */
            status: string;
            /** Version */
            version?: string | null;
        };
        /**
         * JobSummary
         * @description Summary of a job for listing.
         */
        JobSummary: {
            /**
             * Created At
             * @description Unix timestamp (seconds) for when the job was created. Mirrors received_at; exposed so clients have an explicit creation time.
             * @default 0
             */
            created_at: number;
            /** Failure Reason */
            failure_reason?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Progress
             * @description Job completion as a decimal from 0 (not started) to 1 (complete).
             */
            progress: number;
            /** Received At */
            received_at: number;
            /** Status */
            status: string;
        };
        /**
         * JobsListResponse
         * @description Response for listing jobs.
         */
        JobsListResponse: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Jobs */
            jobs: components["schemas"]["JobSummary"][];
            /** Org Id */
            org_id?: string | null;
        };
        /** ParseChunk */
        ParseChunk: {
            grounding: components["schemas"]["ParseGrounding"];
            /** Id */
            id: string;
            /** Markdown */
            markdown: string;
            /** Type */
            type: string;
        };
        /** ParseGrounding */
        ParseGrounding: {
            box: components["schemas"]["ParseGroundingBox"];
            /** Page */
            page: number;
        };
        /** ParseGroundingBox */
        ParseGroundingBox: {
            /** Bottom */
            bottom: number;
            /** Left */
            left: number;
            /** Right */
            right: number;
            /** Top */
            top: number;
        };
        /** ParseMetadata */
        ParseMetadata: {
            /** Credit Usage */
            credit_usage: number;
            /** Duration Ms */
            duration_ms: number;
            /** Failed Pages */
            failed_pages?: number[];
            /** Filename */
            filename: string;
            /** Job Id */
            job_id: string;
            /** Org Id */
            org_id: string | null;
            /** Page Count */
            page_count: number;
            /** Version */
            version: string | null;
        };
        /** ParseRequestWithEncryptedPassword */
        ParseRequestWithEncryptedPassword: {
            /**
             * Custom Prompts
             * @description Optional JSON string mapping chunk types to custom parsing prompts. Only the `figure` key is supported, for example '{"figure":"Describe axis labels in detail."}'.
             */
            custom_prompts?: string | null;
            /**
             * Document
             * @description A file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document_url` parameter must be provided.
             */
            document?: string | null;
            /**
             * Document Url
             * @description The URL to the file to be parsed. The file can be a PDF or an image. See the list of supported file types here: https://docs.landing.ai/ade/ade-file-types. Either this parameter or the `document` parameter must be provided.
             */
            document_url?: string | null;
            /**
             * Model
             * @description The version of the model to use for parsing.
             */
            model?: string | null;
            /**
             * Password
             * @description Password for encrypted document files. If the document is password-protected, provide the password to decrypt and process the document. Ignored for unencrypted documents.
             */
            password?: string | null;
            /** @description If you want to split documents into smaller sections, include the split parameter. Set the parameter to page to split documents at the page level. The splits object in the API output will contain a set of data for each page. */
            split?: components["schemas"]["SplitType"] | null;
        };
        /** ParseResponse */
        ParseResponse: {
            /** Chunks */
            chunks: components["schemas"]["ParseChunk"][];
            /** Grounding */
            grounding?: {
                [key: string]: components["schemas"]["ParseResponseGrounding"] | components["schemas"]["ParseResponseTableCellGrounding"];
            };
            /** Markdown */
            markdown: string;
            metadata: components["schemas"]["ParseMetadata"];
            /** Splits */
            splits: components["schemas"]["ParseSplit"][];
        };
        /** ParseResponseGrounding */
        ParseResponseGrounding: {
            box: components["schemas"]["ParseGroundingBox"];
            /** Confidence */
            confidence?: number | null;
            /** Low Confidence Spans */
            low_confidence_spans?: components["schemas"]["Patch"][];
            /** Page */
            page: number;
            type: components["schemas"]["GroundingType"];
        };
        /** ParseResponseTableCellGrounding */
        ParseResponseTableCellGrounding: {
            box: components["schemas"]["ParseGroundingBox"];
            /** Confidence */
            confidence?: number | null;
            /** Page */
            page: number;
            position?: components["schemas"]["ParseResponseTableCellGroundingPosition"] | null;
            type: components["schemas"]["GroundingType"];
        };
        /** ParseResponseTableCellGroundingPosition */
        ParseResponseTableCellGroundingPosition: {
            /** Chunk Id */
            chunk_id: string;
            /** Col */
            col: number;
            /** Colspan */
            colspan: number;
            /** Row */
            row: number;
            /** Rowspan */
            rowspan: number;
        };
        /** ParseSplit */
        ParseSplit: {
            /** Chunks */
            chunks: string[];
            /** Class */
            class: string;
            /** Identifier */
            identifier: string;
            /** Markdown */
            markdown: string;
            /** Pages */
            pages: number[];
        };
        /** Patch */
        Patch: {
            /** Confidence */
            confidence: number;
            /** Span */
            span: [
                number,
                number
            ];
            /** Text */
            text: string;
        };
        /**
         * SectionMetadata
         * @description Public metadata for section response.
         */
        SectionMetadata: {
            /** Credit Usage */
            credit_usage: number;
            /** Duration Ms */
            duration_ms: number;
            /** Filename */
            filename: string;
            /**
             * Job Id
             * @default
             */
            job_id: string;
            /** Org Id */
            org_id?: string | null;
            /** Version */
            version?: string | null;
        };
        /**
         * SectionRequest
         * @description Request model for section endpoint.
         */
        SectionRequest: {
            /**
             * Guidelines
             * @description Natural-language instructions to control hierarchy. Examples: 'Group by topic', 'Treat each numbered section as a top-level entry'.
             */
            guidelines?: string | null;
            /**
             * Markdown
             * @description Parsed markdown with reference anchors (<a id='...'></a>). This is the markdown field from a parse response.
             */
            markdown?: string | null;
            /**
             * Markdown Url
             * @description URL to fetch the markdown from.
             */
            markdown_url?: string | null;
            /**
             * Model
             * @description Section model version. Defaults to latest.
             */
            model?: string | null;
        };
        /**
         * SectionResponse
         * @description Response model for section endpoint.
         */
        SectionResponse: {
            metadata: components["schemas"]["SectionMetadata"];
            /** Table Of Contents */
            table_of_contents: components["schemas"]["SectionTOCEntry"][];
            /** Table Of Contents Md */
            table_of_contents_md: string;
        };
        /**
         * SectionTOCEntry
         * @description A single entry in the flat table of contents.
         */
        SectionTOCEntry: {
            /** Level */
            level: number;
            /** Section Number */
            section_number: string;
            /** Start Reference */
            start_reference: string;
            /** Title */
            title: string;
        };
        /**
         * SplitClass
         * @description Model for split classification option.
         */
        SplitClass: {
            /**
             * Description
             * @description Detailed description of what this split type represents
             */
            description?: string | null;
            /**
             * Identifier
             * @description Identifier to partition/group the splits by
             */
            identifier?: string | null;
            /**
             * Name
             * @description Name of the split classification type
             */
            name: string;
        };
        /**
         * SplitData
         * @description Split data for split classification endpoint.
         */
        SplitData: {
            /** Classification */
            classification: string;
            /** Identifier */
            identifier: string | null;
            /** Markdowns */
            markdowns: string[];
            /** Pages */
            pages: number[];
        };
        /**
         * SplitMetadata
         * @description Metadata for split classification response.
         */
        SplitMetadata: {
            /** Credit Usage */
            credit_usage: number;
            /** Duration Ms */
            duration_ms: number;
            /** Filename */
            filename: string;
            /**
             * Job Id
             * @description Inference history job ID
             * @default
             */
            job_id: string;
            /**
             * Org Id
             * @description Organization ID
             */
            org_id?: string | null;
            /** Page Count */
            page_count: number;
            /**
             * Version
             * @description Model version used for split classification
             */
            version?: string | null;
        };
        /**
         * SplitRequest
         * @description Request model for split classification endpoint.
         */
        SplitRequest: {
            /**
             * Markdown
             * @description The Markdown file or Markdown content to split.
             */
            markdown?: string | null;
            /**
             * Markdown Url
             * @description The URL to the Markdown file to split.
             */
            markdown_url?: string | null;
            /**
             * Model
             * @description Model version to use for split classification. Defaults to the latest version.
             * @default split-20251105
             */
            model: string | null;
            /**
             * Split Class
             * @description List of split classification options/configuration. Can be provided as JSON string in form data.
             */
            split_class: components["schemas"]["SplitClass"][];
        };
        /**
         * SplitResponse
         * @description Response model for split classification endpoint.
         */
        SplitResponse: {
            metadata: components["schemas"]["SplitMetadata"];
            /** Splits */
            splits: components["schemas"]["SplitData"][];
        };
        /**
         * SplitType
         * @constant
         * @enum {string}
         */
        SplitType: "page";
        /**
         * SpreadsheetChunk
         * @description Chunk from spreadsheet parsing.
         *
         *     Can represent:
         *     - Table chunks from spreadsheet cells
         *     - Parsed content chunks from embedded images (text, table, figure, etc.)
         */
        SpreadsheetChunk: {
            /** @description Visual grounding coordinates from /parse API (only for chunks derived from embedded images) */
            grounding?: components["schemas"]["ParseGrounding"] | null;
            /**
             * Id
             * @description Chunk ID - format: '{sheet_name}-{cell_range}' for tables, '{sheet_name}-image-{index}-{anchor_cell}-chunk-{i}-{type}' for parsed image chunks
             */
            id: string;
            /**
             * Markdown
             * @description Chunk content as HTML table with anchor tag (for tables) or parsed markdown content (for chunks from images)
             */
            markdown: string;
            /**
             * Type
             * @description Chunk type: 'table' for spreadsheet tables, or types from /parse (text, table, figure, form, etc.) for chunks derived from embedded images
             */
            type: string;
        };
        /**
         * SpreadsheetParseMetadata
         * @description Metadata for spreadsheet parsing result.
         */
        SpreadsheetParseMetadata: {
            /**
             * Credit Usage
             * @description Credits charged
             * @default 0
             */
            credit_usage: number;
            /**
             * Duration Ms
             * @description Processing duration in milliseconds
             */
            duration_ms: number;
            /**
             * Filename
             * @description Original filename
             */
            filename: string;
            /**
             * Job Id
             * @description Inference history job ID
             * @default
             */
            job_id: string;
            /**
             * Org Id
             * @description Organization ID
             */
            org_id?: string | null;
            /**
             * Sheet Count
             * @description Number of sheets processed
             */
            sheet_count: number;
            /**
             * Total Cells
             * @description Total non-empty cells across all sheets
             */
            total_cells: number;
            /**
             * Total Chunks
             * @description Total chunks (tables + images) extracted
             */
            total_chunks: number;
            /**
             * Total Images
             * @description Total images extracted
             * @default 0
             */
            total_images: number;
            /**
             * Total Rows
             * @description Total rows across all sheets
             */
            total_rows: number;
            /**
             * Version
             * @description Model version for parsing images
             */
            version?: string | null;
        };
        /**
         * SpreadsheetParseResponse
         * @description Response from /ade/parse-spreadsheet endpoint.
         *
         *     Similar structure to ParseResponse but without grounding.
         */
        SpreadsheetParseResponse: {
            /**
             * Chunks
             * @description List of table chunks (HTML)
             */
            chunks: components["schemas"]["SpreadsheetChunk"][];
            /**
             * Markdown
             * @description Full document as HTML with anchor tags and tables
             */
            markdown: string;
            /** @description Parsing metadata */
            metadata: components["schemas"]["SpreadsheetParseMetadata"];
            /**
             * Splits
             * @description Sheet-based splits
             */
            splits: components["schemas"]["SpreadsheetSplit"][];
        };
        /**
         * SpreadsheetSplit
         * @description Sheet-based split from spreadsheet parsing.
         *
         *     Similar to ParseSplit but grouped by sheet instead of page.
         *     Supports both 'page' (per-sheet) and 'full' (all sheets) split types.
         */
        SpreadsheetSplit: {
            /**
             * Chunks
             * @description Chunk IDs in this split
             */
            chunks: string[];
            /**
             * Class
             * @description Split class: 'page' for per-sheet splits, 'full' for single split with all content
             */
            class: string;
            /**
             * Identifier
             * @description Split identifier: sheet name for 'page' splits, 'full' for full split
             */
            identifier: string;
            /**
             * Markdown
             * @description Combined markdown for this split
             */
            markdown: string;
            /**
             * Sheets
             * @description Sheet indices: single element for 'page' splits, all indices for 'full' split
             */
            sheets: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    tool_ade_classify_v1_ade_classify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ClassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassifyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_extract_v1_ade_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Extraction completed with success but there was a schema validation error. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tool_ade_build_schema_v1_ade_extract_build_schema_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["BuildSchemaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSchemaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_list_extract_jobs_v1_ade_extract_jobs_get: {
        parameters: {
            query?: {
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
                /** @description Filter by job status. */
                status?: ("cancelled" | "completed" | "failed" | "pending" | "processing") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_extract_jobs_v1_ade_extract_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AsyncExtractRequest"];
            };
        };
        responses: {
            /** @description Job queued successfully */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "job_id": "12345678-1234-1234-1234-123456789012"
                     *     }
                     */
                    "application/json": components["schemas"]["JobCreationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tool_ade_get_extract_jobs_v1_ade_extract_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractJobStatusResponse"];
                };
            };
            /** @description Extraction completed with success but there was a schema validation error. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractJobStatusResponse"];
                };
            };
            /** @description Job ID not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_parse_v1_ade_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ParseRequestWithEncryptedPassword"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description There were some pages that failed to be parsed. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tool_ade_list_parse_jobs_v1_ade_parse_jobs_get: {
        parameters: {
            query?: {
                /** @description Page number (0-indexed) */
                page?: number;
                /** @description Number of items per page */
                pageSize?: number;
                /** @description Filter by job status. */
                status?: ("cancelled" | "completed" | "failed" | "pending" | "processing") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_parse_jobs_v1_ade_parse_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["AsyncParseRequestWithEncryptedPassword"];
            };
        };
        responses: {
            /** @description Job queued successfully */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "job_id": "12345678-1234-1234-1234-123456789012"
                     *     }
                     */
                    "application/json": components["schemas"]["JobCreationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tool_ade_get_parse_jobs_v1_ade_parse_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description There were some pages that failed to be parsed. */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Job ID not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_section_v1_ade_section_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tool_ade_split_v1_ade_split_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SplitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SplitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
