/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stage an input file
         * @description Stage bytes on the data plane; pass the returned ``file_ref`` in
         *     job inputs (the contract request types take ``*_ref`` fields).
         */
        post: operations["stage_file_v1_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Extract
         * @description Extract structured data from a Markdown document according to a JSON schema, with character-span grounding into the source Markdown. Runs synchronously and returns the result inline.
         */
        post: operations["v2-extract_run_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/extract/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE List Extract Jobs
         * @description List your Extract jobs, newest first.
         */
        get: operations["v2-extract_list_jobs"];
        put?: never;
        /**
         * ADE Extract Jobs
         * @description Extract structured data from a Markdown document according to a JSON schema, with character-span grounding into the source Markdown. Runs asynchronously and returns a job ID; use it to poll for status and retrieve the result once processing completes.
         */
        post: operations["v2-extract_create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/extract/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE Get Extract Jobs
         * @description Get the status of an async Extract job, including its result once the job has completed.
         */
        get: operations["v2-extract_get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ADE Parse
         * @description Parse a document and return the parse response inline.
         */
        post: operations["parse_run_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/parse/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ADE List Parse Jobs */
        get: operations["parse_list_jobs"];
        put?: never;
        /**
         * ADE Parse Jobs
         * @description Parse a document asynchronously. Returns a job ID; use it to poll for the job's status and retrieve the parse result once processing completes.
         */
        post: operations["parse_create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/parse/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ADE Get Parse Jobs
         * @description Get the status of an async parse job. Once the job has ``completed``, ``data`` carries the parse result (or ``output_url`` when ``output_save_url`` was set).
         */
        get: operations["parse_get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run v2-workflow (sync)
         * @description Run synchronously and return the result inline.
         *
         *     Accepts ``application/json`` (the request fields as the body) or
         *     ``multipart/form-data`` (file fields are staged automatically).
         *
         *     Returns **504** if the work does not finish within the wait
         *     window — long-running work belongs on the async ``POST
         *     {path}/jobs`` route, which returns 202 immediately and is polled
         *     via ``GET {path}/jobs/{job_id}``. On a 504 the workflow is
         *     CANCELLED (a sync caller can never collect the result); a retry
         *     starts the work over as a fresh job.
         */
        post: operations["v2-workflow_run_sync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/workflow/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List v2-workflow jobs */
        get: operations["v2-workflow_list_jobs"];
        put?: never;
        /** Create v2-workflow job */
        post: operations["v2-workflow_create_job"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/workflow/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get v2-workflow job
         * @description Poll a job.
         *
         *     Returns ``{job_id, status, created_at}`` plus ``completed_at`` and
         *     ``result`` (on ``completed``) or ``error: {code, message}`` (on
         *     ``failed``). Statuses: ``pending`` → ``processing`` →
         *     ``completed`` | ``failed``.
         */
        get: operations["v2-workflow_get_job"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BaseElementOptions */
        BaseElementOptions: {
            /**
             * Caption
             * @default true
             */
            caption: boolean;
        };
        /** BlocksOptions */
        BlocksOptions: {
            attestation?: components["schemas"]["BaseElementOptions"];
            card?: components["schemas"]["BaseElementOptions"];
            figure?: components["schemas"]["FigureOptions"];
            logo?: components["schemas"]["BaseElementOptions"];
            marginalia?: components["schemas"]["BaseElementOptions"];
            scan_code?: components["schemas"]["BaseElementOptions"];
            table?: components["schemas"]["TableOptions"];
            text?: components["schemas"]["BaseElementOptions"];
        };
        /** Body_stage_file_v1_files_post */
        Body_stage_file_v1_files_post: {
            /** File */
            file: string;
        };
        /** Document */
        Document: {
            /**
             * Children
             * @description The pages of the document, in source order.
             */
            children?: components["schemas"]["Page"][];
            /**
             * Type
             * @description The node type. Identifies this node as the root of the structure tree.
             * @default document
             * @constant
             */
            type: "document";
        };
        /**
         * Element
         * @description Hierarchical document element. All non-page elements share this shape.
         *
         *     Keys off `type`; optional fields are excluded from the serialized JSON
         *     via ``exclude_none=True`` when not set.
         */
        Element: {
            /**
             * Children
             * @description The cells (`table_cell` elements) of a `table` element. Present only when `type` is `table`.
             * @default null
             */
            children: components["schemas"]["Element"][] | null;
            /**
             * Col
             * @description 0-indexed column position of this cell within its parent `table`. Present only on `table_cell` elements.
             * @default null
             */
            col: number | null;
            /**
             * Colspan
             * @description Number of columns this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.
             * @default null
             */
            colspan: number | null;
            /**
             * Id
             * @description A unique identifier for this element within the document. Use it to look up the element's entry in the top-level `grounding` map; treat the value as opaque.
             */
            id: string;
            /**
             * Row
             * @description 0-indexed row position of this cell within its parent `table`. Present only on `table_cell` elements.
             * @default null
             */
            row: number | null;
            /**
             * Rowspan
             * @description Number of rows this cell spans. `1` for unmerged cells. Present only on `table_cell` elements.
             * @default null
             */
            rowspan: number | null;
            /**
             * Span
             * @description Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this element.
             */
            span: [
                number,
                number
            ];
            /**
             * Type
             * @description The element type. Determines which optional fields appear on this element.
             * @enum {string}
             */
            type: "text" | "table" | "table_cell" | "figure" | "marginalia" | "attestation" | "logo" | "card" | "scan_code";
        };
        /** FigureOptions */
        FigureOptions: {
            /**
             * Caption
             * @default true
             */
            caption: boolean;
        };
        /**
         * GroundingDocument
         * @description Root of the `grounding` tree. Mirrors the hierarchy of `structure`
         *     (`document → page → element → table_cell`), carrying the spatial data
         *     (`box`, `parts`) that `structure` deliberately omits.
         */
        GroundingDocument: {
            /**
             * Children
             * @description The pages of the document, in source order — the same order as `structure.children`.
             */
            children?: components["schemas"]["GroundingPage"][];
            /**
             * Type
             * @description The node type. Identifies this node as the root of the grounding tree.
             * @default document
             * @constant
             */
            type: "document";
        };
        /**
         * GroundingElement
         * @description Spatial grounding for one document element.
         *
         *     Mirrors the element's node in the `structure` tree (same `id`, same `span`)
         *     and layers the spatial data on top: the element-level bounding box, its
         *     fine-grained `parts`, and — for a `table` — its cells nested as `children`.
         */
        GroundingElement: {
            /**
             * Box
             * @description Bounding box `[left, top, right, bottom]` for the full element on the source page, in pixels.
             */
            box: [
                number,
                number,
                number,
                number
            ];
            /**
             * Children
             * @description The cells (`table_cell` grounding nodes) of a `table` element, mirroring the table's `children` in the `structure` tree. Present only when `type` is `table`.
             * @default null
             */
            children: components["schemas"]["GroundingElement"][] | null;
            /**
             * Id
             * @description The element's unique identifier within the document. Matches the same element's `id` in the `structure` tree.
             */
            id: string;
            /**
             * Parts
             * @description Finer-grained grounding segments within the element. Per visual line for `text` and `marginalia`; empty for other element types or when `options.grounding.parts` is `false`.
             */
            parts?: components["schemas"]["GroundingEntry"][];
            /**
             * Span
             * @description Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this element. Matches the element's `span` in the `structure` tree.
             */
            span: [
                number,
                number
            ];
            /**
             * Type
             * @description The element type. Matches the same element's `type` in the `structure` tree.
             * @enum {string}
             */
            type: "text" | "table" | "table_cell" | "figure" | "marginalia" | "attestation" | "logo" | "card" | "scan_code";
        };
        /**
         * GroundingEntry
         * @description One fine-grained grounding segment (line-level or finer).
         */
        GroundingEntry: {
            /**
             * Box
             * @description Bounding box `[left, top, right, bottom]` for this part on the source page, in pixels.
             */
            box: [
                number,
                number,
                number,
                number
            ];
            /**
             * Span
             * @description Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this part.
             */
            span: [
                number,
                number
            ];
        };
        /** GroundingOptions */
        GroundingOptions: {
            /**
             * Parts
             * @default true
             */
            parts: boolean;
        };
        /**
         * GroundingPage
         * @description A page node in the `grounding` tree, mirroring the page in `structure`.
         */
        GroundingPage: {
            /**
             * Children
             * @description Grounding for the elements on this page, in reading order — the same order and `id`s as the page's `children` in the `structure` tree. Empty for failed pages.
             */
            children?: components["schemas"]["GroundingElement"][];
            /**
             * Page
             * @description The 0-indexed page number in the source document. Matches the page's `page` in the `structure` tree.
             */
            page: number;
            /**
             * Span
             * @description Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this page. Zero-length `[n, n]` for failed pages.
             */
            span: [
                number,
                number
            ];
            /**
             * Type
             * @description The node type. Identifies this node as a page in the grounding tree.
             * @default page
             * @constant
             */
            type: "page";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Page */
        Page: {
            /**
             * Children
             * @description The elements detected on this page, in reading order.
             */
            children?: components["schemas"]["Element"][];
            /**
             * Dpi
             * @description DPI used to scale this page's PDF coordinates to pixels (pixels = PDF_points × dpi / 72). Present only for pages that originated from a PDF; omitted for image-input pages (which have no DPI concept — their coordinates are already pixels relative to the original upload) and for pages with `status` `failed`.
             * @default null
             */
            dpi: number | null;
            /**
             * Height
             * @description Page height in pixels. Omitted when `status` is `failed`.
             * @default null
             */
            height: number | null;
            /**
             * Page
             * @description The 0-indexed page number in the source document. Not contiguous when `options.pages` filters out some pages.
             */
            page: number;
            /**
             * Reason
             * @description Failure reason. Present only when `status` is `failed`.
             * @default null
             */
            reason: string | null;
            /**
             * Span
             * @description Unicode code point offsets `[start, end)` in the top-level `markdown` string covered by this page. Zero-length `[n, n]` for failed pages.
             */
            span: [
                number,
                number
            ];
            /**
             * Status
             * @description Whether this page was parsed successfully (`ok`) or failed (`failed`).
             * @default ok
             * @enum {string}
             */
            status: "ok" | "failed";
            /**
             * Type
             * @description The node type. Identifies this node as a page in the structure tree.
             * @default page
             * @constant
             */
            type: "page";
            /**
             * Width
             * @description Page width in pixels. Omitted when `status` is `failed`.
             * @default null
             */
            width: number | null;
        };
        /**
         * ParseBilling
         * @description Billing summary for one parse request.
         */
        ParseBilling: {
            /**
             * Service Tier
             * @description The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).
             */
            service_tier: ("standard" | "priority") | null;
            /**
             * Total Credits
             * @description Credits charged for this request.
             */
            total_credits: number | null;
        };
        /**
         * ParseMetadata
         * @description Information about a parse request. This is the customer-facing shape —
         *     the internal billing-canonical metadata (``aide_common.parse_schema.ParseMetadata``)
         *     is projected into it at the render boundary (``project_customer_metadata``).
         */
        ParseMetadata: {
            /** @description Billing summary: the service tier and the credits charged. */
            billing: components["schemas"]["ParseBilling"];
            /**
             * Duration Ms
             * @description Total processing time in milliseconds.
             */
            duration_ms: number | null;
            /**
             * Failed Pages
             * @description 0-indexed page numbers that failed to parse. Empty when all pages succeed; failed pages also appear in `structure.children` with `status: failed`.
             */
            failed_pages: number[];
            /**
             * Job Id
             * @description The parse job identifier — always server-minted and unique per submit. On the async `/jobs` route this is the id the caller polls. Correlates with the job's entry in your billing dashboard.
             */
            job_id: string | null;
            /**
             * Markdown Chars
             * @description Number of Unicode code points in the returned `markdown` string.
             */
            markdown_chars: number | null;
            /**
             * Model Version
             * @description The exact model snapshot that parsed the document, e.g. `dpt-3-pro-20260710`.
             */
            model_version: string | null;
            /**
             * Page Count
             * @description Total number of pages in the source document. Includes pages filtered out by `options.pages`; the actual returned pages are in `structure.children`.
             */
            page_count: number | null;
        };
        /**
         * ParseResponse
         * @description The parse result: the full document as `markdown`, its hierarchical
         *     `structure`, per-element spatial `grounding`, and request `metadata`.
         */
        ParseResponse: {
            /** @description The document's spatial grounding, as a tree mirroring `structure` (`document → page → element → table_cell`). Each element node carries the same `id` and `span` as in `structure`, plus its bounding box and finer-grained parts. */
            grounding: components["schemas"]["GroundingDocument"];
            /**
             * Markdown
             * @description The full document as a single Markdown string, in reading order.
             */
            markdown: string;
            /** @description Information about the request: model version, page count, duration, billing, and more. */
            metadata: components["schemas"]["ParseMetadata"];
            /** @description The document's hierarchical structure: pages and the elements detected on each page. Spatial information for each element is in `grounding`. */
            structure: components["schemas"]["Document"];
        };
        /**
         * PrebuiltWorkflowStep
         * @description A Phase 1 step: references a server-defined pipeline by name.
         *
         *     The ``name`` identifies the prebuilt pipeline to run AND becomes the key
         *     under which this step's result appears in the response ``output`` map.
         *     The ``document`` field is a reference into the ``inputs`` namespace
         *     (``"$inputs.<logical-name>"``).
         */
        PrebuiltWorkflowStep: {
            /**
             * Document
             * @description Reference into the ``inputs`` namespace, e.g. ``"$inputs.report"``. The referenced input must be declared in the ``inputs`` form field.
             */
            document: string;
            /**
             * Name
             * @description Workflow to run — doubles as the result key in ``output``. v1 only: ``"parse-extract"``.
             * @constant
             */
            name: "parse-extract";
            /**
             * @description Parse + extract options for this step. Omit for defaults.
             * @default null
             */
            options: components["schemas"]["WorkflowStepOptions"] | null;
            /**
             * Schema
             * @description JSON Schema for fields to extract.
             * @example {
             *       "properties": {
             *         "revenue": {
             *           "type": "string"
             *         }
             *       },
             *       "type": "object"
             *     }
             */
            schema: {
                [key: string]: unknown;
            };
        };
        /** TableOptions */
        TableOptions: {
            /**
             * Caption
             * @default true
             */
            caption: boolean;
            /**
             * Format
             * @default html
             * @enum {string}
             */
            format: "markdown" | "html";
        };
        /**
         * V2Billing
         * @description Billing summary: the service tier the request ran in and the credits
         *     charged.
         */
        V2Billing: {
            /**
             * Service Tier
             * @description The service tier the request ran in: `standard` or `priority`. A sync request reports `priority` (same lane, same price).
             * @default null
             */
            service_tier: ("standard" | "priority") | null;
            /**
             * Total Credits
             * @description Credits charged for this request.
             * @default null
             */
            total_credits: number | null;
        };
        /**
         * V2ExtractMetadata
         * @description Response metadata for a v2 extract call.
         */
        V2ExtractMetadata: {
            /** @description Billing summary: the service tier the request ran in and the credits charged. */
            billing?: components["schemas"]["V2Billing"] | null;
            /**
             * Credit Usage
             * @description Credits billed for this request.
             * @default 0
             */
            credit_usage: number;
            /**
             * Doc Id
             * @description Present when the input markdown contained a ``<!-- doc_id=<id> -->`` comment (embedded by ``POST /v2/parse``). Links this extract call to the originating parse job.
             * @default null
             */
            doc_id: string | null;
            /**
             * Duration Ms
             * @description End-to-end request duration in milliseconds.
             */
            duration_ms: number;
            /**
             * Job Id
             * @description Gateway job id (workflow id). Matches the ``x-request-id`` the gateway minted for this request and the billing row id in vision-agent.
             */
            job_id: string;
            /**
             * Version
             * @description Resolved model version.
             */
            version: string;
        };
        /**
         * V2ExtractOptions
         * @description Extraction options (``docs/extract-v2-proposal.md`` → Options).
         */
        V2ExtractOptions: {
            /**
             * Strict
             * @description When ``true``, returns HTTP 422 if the schema contains fields the model cannot extract. When ``false`` (default), unsupported fields are skipped and extraction continues.
             * @default false
             */
            strict: boolean;
        };
        /**
         * V2WorkflowMetadata
         * @description Response metadata for a v2 workflow call
         *     (``docs/pipeline-v2-proposal.md`` → Top-level metadata).
         */
        V2WorkflowMetadata: {
            /** @description Billing summary: the service tier the request ran in and the credits charged. */
            billing?: components["schemas"]["V2Billing"] | null;
            /**
             * Credit Usage
             * @description Combined credits billed for this request (parse + extract).
             * @default 0
             */
            credit_usage: number;
            /**
             * Duration Ms
             * @description Total end-to-end duration across all stages in milliseconds.
             */
            duration_ms: number;
            /**
             * Job Id
             * @description Gateway job id (workflow id).
             */
            job_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkflowDocumentInput
         * @description One declared document input in the ``inputs`` map.
         *
         *     A caller supplies exactly one of ``document`` or ``document_url``:
         *
         *     * ``document`` — name of a multipart form part carrying the raw bytes. The
         *       gateway stages those bytes internally before the workflow runs.
         *     * ``document_url`` — public URL (SSRF-validated at submit; fetched and staged
         *       by the gateway before the workflow starts).
         */
        WorkflowDocumentInput: {
            /**
             * Document
             * @description Name of the multipart form part carrying the document bytes. The gateway resolves this to an internal ref before validation; it is not stored in the final request object.
             * @default null
             * @example report_pdf
             */
            document: string | null;
            /**
             * Document Url
             * @description URL to fetch the document from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time.
             * @default null
             */
            document_url: string | null;
        };
        /**
         * WorkflowStepOptions
         * @description Unified options for the ``parse-extract`` prebuilt step.
         *
         *     ``pages`` applies to the parse stage; ``strict`` applies to the extract
         *     stage. Omit entirely to use each stage's defaults.
         */
        WorkflowStepOptions: {
            /**
             * Pages
             * @description 0-indexed page indices to process. ``null`` = all pages. Negative indices are rejected; indices ≥ page_count are silently ignored.
             * @default null
             */
            pages: number[] | null;
            /**
             * Strict
             * @description When ``true``, returns 422 if the schema contains fields the model cannot extract. When ``false``, unsupported fields are skipped.
             * @default false
             */
            strict: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    stage_file_v1_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_stage_file_v1_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-extract_run_sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Markdown
                     * @description Markdown string to extract from, or a multipart FILE part carrying the markdown (large inputs — uploads are staged by the gateway). Can come from any source — LandingAI parse output, a third-party parser, or hand-authored text. When the markdown was produced by ``POST /v2/parse``, it ends with a ``<!-- doc_id=<id> -->`` comment that the service reads automatically and echoes as ``metadata.doc_id``.
                     * @default null
                     */
                    markdown?: string | null;
                    /**
                     * Markdown Url
                     * @description URL to fetch the markdown from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time.
                     * @default null
                     */
                    markdown_url?: string | null;
                    /**
                     * Model
                     * @description The version of the model to use for extraction. Use ``extract-latest`` to use the latest version.
                     * @default null
                     */
                    model?: string | null;
                    /**
                     * @description Extraction options (``strict``). Omit for defaults.
                     * @default null
                     */
                    options?: components["schemas"]["V2ExtractOptions"] | null;
                    /**
                     * Schema
                     * @description JSON Schema describing the fields to extract. The schema must be an object type with a ``properties`` map of field names to their types and descriptions.
                     * @example {
                     *       "properties": {
                     *         "revenue": {
                     *           "description": "Q1 revenue figure",
                     *           "type": "string"
                     *         },
                     *         "summary": {
                     *           "description": "Executive summary",
                     *           "type": "string"
                     *         }
                     *       },
                     *       "type": "object"
                     *     }
                     */
                    schema: {
                        [key: string]: unknown;
                    };
                };
                "multipart/form-data": {
                    markdown?: string;
                    /**
                     * Markdown Url
                     * @description URL to fetch the markdown from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time. JSON-serialized string in form data.
                     * @default null
                     */
                    markdown_url?: string | null;
                    /**
                     * Model
                     * @description The version of the model to use for extraction. Use ``extract-latest`` to use the latest version. JSON-serialized string in form data.
                     * @default null
                     */
                    model?: string | null;
                    /**
                     * @description Extraction options (``strict``). Omit for defaults. JSON-serialized string in form data.
                     * @default null
                     */
                    options?: components["schemas"]["V2ExtractOptions"] | null;
                    /**
                     * Schema
                     * @description JSON Schema describing the fields to extract. The schema must be an object type with a ``properties`` map of field names to their types and descriptions. JSON-serialized string in form data.
                     * @example {
                     *       "properties": {
                     *         "revenue": {
                     *           "description": "Q1 revenue figure",
                     *           "type": "string"
                     *         },
                     *         "summary": {
                     *           "description": "Executive summary",
                     *           "type": "string"
                     *         }
                     *       },
                     *       "type": "object"
                     *     }
                     */
                    schema: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description v2-extract result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Extraction
                         * @description Extracted values conforming to the request ``schema``.
                         */
                        extraction: {
                            [key: string]: unknown;
                        };
                        /**
                         * Extraction Metadata
                         * @description Per-field metadata, mirroring ``extraction`` with leaf values replaced by ``{value, spans}`` objects.
                         */
                        extraction_metadata: {
                            [key: string]: unknown;
                        };
                        /**
                         * Markdown
                         * @description Echoed input markdown.
                         */
                        markdown: string;
                        /** @description Request metadata (job_id, version, duration_ms, doc_id, credit_usage). */
                        metadata: components["schemas"]["V2ExtractMetadata"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-extract_list_jobs": {
        parameters: {
            query?: {
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                page_size?: number;
                /** @description Filter by job status. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's jobs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        has_more?: boolean;
                        jobs?: {
                            completed_at?: string | null;
                            created_at?: string | null;
                            failure_reason?: string | null;
                            job_id?: string;
                            /** @enum {string} */
                            status?: "pending" | "processing" | "completed" | "failed";
                            version?: string | null;
                        }[];
                        page?: number;
                        page_size?: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-extract_create_job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Markdown
                     * @description Markdown string to extract from, or a multipart FILE part carrying the markdown (large inputs — uploads are staged by the gateway). Can come from any source — LandingAI parse output, a third-party parser, or hand-authored text. When the markdown was produced by ``POST /v2/parse``, it ends with a ``<!-- doc_id=<id> -->`` comment that the service reads automatically and echoes as ``metadata.doc_id``.
                     * @default null
                     */
                    markdown?: string | null;
                    /**
                     * Markdown Url
                     * @description URL to fetch the markdown from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time.
                     * @default null
                     */
                    markdown_url?: string | null;
                    /**
                     * Model
                     * @description The version of the model to use for extraction. Use ``extract-latest`` to use the latest version.
                     * @default null
                     */
                    model?: string | null;
                    /**
                     * @description Extraction options (``strict``). Omit for defaults.
                     * @default null
                     */
                    options?: components["schemas"]["V2ExtractOptions"] | null;
                    /**
                     * Schema
                     * @description JSON Schema describing the fields to extract. The schema must be an object type with a ``properties`` map of field names to their types and descriptions.
                     * @example {
                     *       "properties": {
                     *         "revenue": {
                     *           "description": "Q1 revenue figure",
                     *           "type": "string"
                     *         },
                     *         "summary": {
                     *           "description": "Executive summary",
                     *           "type": "string"
                     *         }
                     *       },
                     *       "type": "object"
                     *     }
                     */
                    schema: {
                        [key: string]: unknown;
                    };
                    /** @description Async service tier. ``priority`` runs in the fast lane at the sync billing rate; absent → ``standard``. */
                    service_tier?: ("standard" | "priority") | null;
                };
                "multipart/form-data": {
                    markdown?: string;
                    /**
                     * Markdown Url
                     * @description URL to fetch the markdown from. Must be a public http(s) URL; private/loopback IPs are rejected at submit time. JSON-serialized string in form data.
                     * @default null
                     */
                    markdown_url?: string | null;
                    /**
                     * Model
                     * @description The version of the model to use for extraction. Use ``extract-latest`` to use the latest version. JSON-serialized string in form data.
                     * @default null
                     */
                    model?: string | null;
                    /**
                     * @description Extraction options (``strict``). Omit for defaults. JSON-serialized string in form data.
                     * @default null
                     */
                    options?: components["schemas"]["V2ExtractOptions"] | null;
                    /**
                     * Schema
                     * @description JSON Schema describing the fields to extract. The schema must be an object type with a ``properties`` map of field names to their types and descriptions. JSON-serialized string in form data.
                     * @example {
                     *       "properties": {
                     *         "revenue": {
                     *           "description": "Q1 revenue figure",
                     *           "type": "string"
                     *         },
                     *         "summary": {
                     *           "description": "Executive summary",
                     *           "type": "string"
                     *         }
                     *       },
                     *       "type": "object"
                     *     }
                     */
                    schema: {
                        [key: string]: unknown;
                    };
                    /** @description Async service tier. ``priority`` runs in the fast lane at the sync billing rate; absent → ``standard``. */
                    service_tier?: ("standard" | "priority") | null;
                };
            };
        };
        responses: {
            /** @description Job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at?: string | null;
                        job_id?: string;
                        /** @enum {string} */
                        status?: "pending" | "processing" | "completed" | "failed";
                    };
                };
            };
        };
    };
    "v2-extract_get_job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the job to retrieve, as returned by the create-job request. */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status / result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Present once the job is terminal. */
                        completed_at?: string;
                        created_at?: string | null;
                        /** @description Present once status is ``failed``. */
                        error?: {
                            /** @description Stable error code (``internal_error`` when unmapped). */
                            code?: string;
                            message?: string;
                        };
                        job_id?: string;
                        /** @description Best-effort progress, present while processing only for jobs that report it. */
                        progress?: unknown;
                        /** @description Present once status is ``completed``. */
                        result?: {
                            /**
                             * Extraction
                             * @description Extracted values conforming to the request ``schema``.
                             */
                            extraction: {
                                [key: string]: unknown;
                            };
                            /**
                             * Extraction Metadata
                             * @description Per-field metadata, mirroring ``extraction`` with leaf values replaced by ``{value, spans}`` objects.
                             */
                            extraction_metadata: {
                                [key: string]: unknown;
                            };
                            /**
                             * Markdown
                             * @description Echoed input markdown.
                             */
                            markdown: string;
                            /** @description Request metadata (job_id, version, duration_ms, doc_id, credit_usage). */
                            metadata: components["schemas"]["V2ExtractMetadata"];
                        } | null;
                        /** @enum {string} */
                        status?: "pending" | "processing" | "completed" | "failed";
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_run_sync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to parse. The file must be a PDF or image; see the list of [supported file types](https://docs.landing.ai/dpt3/file-types). Provide either `document` or `document_url`, not both.
                     */
                    document?: string;
                    /** @description A publicly accessible URL to the file to parse. The file must be a PDF or image; see the list of [supported file types](https://docs.landing.ai/dpt3/file-types). Provide either `document` or `document_url`, not both. */
                    document_url?: string;
                    /** @description The DPT-3 model snapshot to use for this request. Accepts a dated snapshot (for example, `dpt-3-pro-20260710`), the `dpt-3-pro-latest` alias, or the bare `dpt-3-pro` family name (equivalent to `dpt-3-pro-latest`). Defaults to the latest DPT-3 Pro snapshot. */
                    model?: string;
                    /**
                     * ParseOptions
                     * @description Optional object that customizes the parse. Use it to select which pages to process, adjust how content appears in the Markdown, or control how much detail the response includes. Sent as a JSON-serialized string in form data.
                     */
                    options?: {
                        blocks?: components["schemas"]["BlocksOptions"];
                        /**
                         * Dpi
                         * @description Resolution for PDF coordinate scaling. Bounding box coordinates and page dimensions are returned in pixels at this DPI (pixels = PDF_points × dpi / 72). Allowed range: 72–300. Has no effect for image inputs.
                         * @default 200
                         */
                        dpi?: number;
                        grounding?: components["schemas"]["GroundingOptions"];
                        /**
                         * Pages
                         * @default null
                         */
                        pages?: number[] | null;
                    };
                    /** @description Encrypted PDFs are not currently supported. Providing a password returns a 422 error; decrypt the file before uploading. */
                    password?: string;
                };
            };
        };
        responses: {
            /** @description The parse response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Partial success (some pages failed to parse) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_list_jobs: {
        parameters: {
            query?: {
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                page_size?: number;
                /** @description Filter by job status. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's jobs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Whether more jobs exist beyond this page; request the next ``page`` to fetch them. */
                        has_more?: boolean;
                        /** @description The caller's parse jobs for this page, newest first. */
                        jobs?: {
                            /** @description Unix timestamp (seconds) for when the job was created. Mirrors ``received_at``; exposed so clients have an explicit creation time. */
                            created_at?: number;
                            /** @description The reason the job failed. Present only when ``status`` is ``failed``. */
                            failure_reason?: string;
                            /** @description The unique identifier for the parse job. */
                            job_id?: string;
                            /** @description Job completion as a decimal from 0 (not started) to 1 (complete). */
                            progress?: number;
                            /** @description Unix timestamp (seconds) for when the job was received. */
                            received_at?: number;
                            /**
                             * @description The job's current status: ``pending``, ``processing``, ``completed``, ``failed``, or ``cancelled``.
                             * @enum {string}
                             */
                            status?: "pending" | "processing" | "completed" | "failed" | "cancelled";
                        }[];
                        /** @description The organization that owns these jobs. */
                        org_id?: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_create_job: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to parse. The file must be a PDF or image; see the list of [supported file types](https://docs.landing.ai/dpt3/file-types). Provide either `document` or `document_url`, not both.
                     */
                    document?: string;
                    /** @description A publicly accessible URL to the file to parse. The file must be a PDF or image; see the list of [supported file types](https://docs.landing.ai/dpt3/file-types). Provide either `document` or `document_url`, not both. */
                    document_url?: string;
                    /** @description The DPT-3 model snapshot to use for this request. Accepts a dated snapshot (for example, `dpt-3-pro-20260710`), the `dpt-3-pro-latest` alias, or the bare `dpt-3-pro` family name (equivalent to `dpt-3-pro-latest`). Defaults to the latest DPT-3 Pro snapshot. */
                    model?: string;
                    /**
                     * ParseOptions
                     * @description Optional object that customizes the parse. Use it to select which pages to process, adjust how content appears in the Markdown, or control how much detail the response includes. Sent as a JSON-serialized string in form data.
                     */
                    options?: {
                        blocks?: components["schemas"]["BlocksOptions"];
                        /**
                         * Dpi
                         * @description Resolution for PDF coordinate scaling. Bounding box coordinates and page dimensions are returned in pixels at this DPI (pixels = PDF_points × dpi / 72). Allowed range: 72–300. Has no effect for image inputs.
                         * @default 200
                         */
                        dpi?: number;
                        grounding?: components["schemas"]["GroundingOptions"];
                        /**
                         * Pages
                         * @default null
                         */
                        pages?: number[] | null;
                    };
                    /** @description Public URL the full response is delivered to; the API response then carries ``output_url`` instead of inline data. */
                    output_save_url?: string;
                    /** @description Encrypted PDFs are not currently supported. Providing a password returns a 422 error; decrypt the file before uploading. */
                    password?: string;
                    /**
                     * @description Async service tier (``POST /jobs`` only). ``priority`` runs in the fast lane at the sync billing rate; absent → ``standard``.
                     * @enum {string}
                     */
                    service_tier?: "standard" | "priority";
                };
            };
        };
        responses: {
            /** @description Job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description The unique identifier for the created parse job. Poll ``GET /v2/parse/jobs/{job_id}`` for its status and result. */
                        job_id: string;
                    };
                };
            };
        };
    };
    parse_get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the job to retrieve, as returned by the create-job request. */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status / result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unix timestamp (seconds) for when the job was created. Mirrors ``received_at``; exposed so clients have an explicit creation time. */
                        created_at?: number | null;
                        /** @description The parse result, present once the job has ``completed`` and ``output_save_url`` was not set. When ``output_save_url`` was set, the result is delivered there and ``output_url`` is returned instead. */
                        data?: components["schemas"]["ParseResponse"] | null;
                        /** @description The reason the job failed. Present only when ``status`` is ``failed``. */
                        failure_reason?: string | null;
                        /** @description The unique identifier for this parse job. */
                        job_id?: string;
                        /** @description The result's ``metadata`` (model version, page count, billing, and more). Present once the job has ``completed``. */
                        metadata?: components["schemas"]["ParseMetadata"] | null;
                        /** @description The organization that owns this job. */
                        org_id?: string | null;
                        /** @description The URL the result was delivered to. Present once the job has ``completed`` and ``output_save_url`` was set; the result is delivered there instead of inline ``data``. */
                        output_url?: string | null;
                        /** @description Job completion progress as a decimal from 0 to 1, where 0 is not started, 1 is finished, and values between 0 and 1 indicate work in progress. */
                        progress?: number;
                        /** @description Unix timestamp (seconds) for when the job was received. */
                        received_at?: number | null;
                        /**
                         * @description The job's current status: ``pending``, ``processing``, ``completed``, ``failed``, or ``cancelled``.
                         * @enum {string}
                         */
                        status?: "pending" | "processing" | "completed" | "failed" | "cancelled";
                        /** @description The model snapshot used to parse the document. */
                        version?: string | null;
                    };
                };
            };
            /** @description Partial success (some pages failed to parse) */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Unix timestamp (seconds) for when the job was created. Mirrors ``received_at``; exposed so clients have an explicit creation time. */
                        created_at?: number | null;
                        /** @description The parse result, present once the job has ``completed`` and ``output_save_url`` was not set. When ``output_save_url`` was set, the result is delivered there and ``output_url`` is returned instead. */
                        data?: components["schemas"]["ParseResponse"] | null;
                        /** @description The reason the job failed. Present only when ``status`` is ``failed``. */
                        failure_reason?: string | null;
                        /** @description The unique identifier for this parse job. */
                        job_id?: string;
                        /** @description The result's ``metadata`` (model version, page count, billing, and more). Present once the job has ``completed``. */
                        metadata?: components["schemas"]["ParseMetadata"] | null;
                        /** @description The organization that owns this job. */
                        org_id?: string | null;
                        /** @description The URL the result was delivered to. Present once the job has ``completed`` and ``output_save_url`` was set; the result is delivered there instead of inline ``data``. */
                        output_url?: string | null;
                        /** @description Job completion progress as a decimal from 0 to 1, where 0 is not started, 1 is finished, and values between 0 and 1 indicate work in progress. */
                        progress?: number;
                        /** @description Unix timestamp (seconds) for when the job was received. */
                        received_at?: number | null;
                        /**
                         * @description The job's current status: ``pending``, ``processing``, ``completed``, ``failed``, or ``cancelled``.
                         * @enum {string}
                         */
                        status?: "pending" | "processing" | "completed" | "failed" | "cancelled";
                        /** @description The model snapshot used to parse the document. */
                        version?: string | null;
                    };
                };
            };
            /** @description Job not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-workflow_run_sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Inputs
                     * @description Named document sources. Each key is a logical name referenced from steps as ``"$inputs.<name>"``. The gateway stages binary multipart uploads internally before the workflow runs.
                     * @example {
                     *       "report": {
                     *         "document": "report_pdf"
                     *       }
                     *     }
                     */
                    inputs: {
                        [key: string]: components["schemas"]["WorkflowDocumentInput"];
                    };
                    /**
                     * Output
                     * @description Optional projection map. Keys are caller-chosen response field names; values are ``$output.<step>.<field>...`` references. Omitted → full results tree returned under ``output``.
                     * @default null
                     * @example {
                     *       "revenue": "$output.parse-extract.extract.extraction.revenue",
                     *       "revenue_box": "$output.parse-extract.ground.revenue"
                     *     }
                     */
                    output?: {
                        [key: string]: string;
                    } | null;
                    /**
                     * Steps
                     * @description Phase 1: a single prebuilt-pipeline step (name must be ``"parse-extract"``). Its result appears in ``output`` under the step's name.
                     * @example [
                     *       {
                     *         "document": "$inputs.report",
                     *         "name": "parse-extract",
                     *         "schema": {
                     *           "properties": {
                     *             "revenue": {
                     *               "type": "string"
                     *             }
                     *           },
                     *           "type": "object"
                     *         }
                     *       }
                     *     ]
                     */
                    steps: components["schemas"]["PrebuiltWorkflowStep"][];
                };
                "multipart/form-data": {
                    /**
                     * Inputs
                     * @description Named document sources. Each key is a logical name referenced from steps as ``"$inputs.<name>"``. The gateway stages binary multipart uploads internally before the workflow runs. JSON-serialized string in form data.
                     * @example {
                     *       "report": {
                     *         "document": "report_pdf"
                     *       }
                     *     }
                     */
                    inputs: {
                        [key: string]: components["schemas"]["WorkflowDocumentInput"];
                    };
                    /**
                     * Output
                     * @description Optional projection map. Keys are caller-chosen response field names; values are ``$output.<step>.<field>...`` references. Omitted → full results tree returned under ``output``. JSON-serialized string in form data.
                     * @default null
                     * @example {
                     *       "revenue": "$output.parse-extract.extract.extraction.revenue",
                     *       "revenue_box": "$output.parse-extract.ground.revenue"
                     *     }
                     */
                    output?: {
                        [key: string]: string;
                    } | null;
                    /**
                     * Steps
                     * @description Phase 1: a single prebuilt-pipeline step (name must be ``"parse-extract"``). Its result appears in ``output`` under the step's name. JSON-serialized string in form data.
                     * @example [
                     *       {
                     *         "document": "$inputs.report",
                     *         "name": "parse-extract",
                     *         "schema": {
                     *           "properties": {
                     *             "revenue": {
                     *               "type": "string"
                     *             }
                     *           },
                     *           "type": "object"
                     *         }
                     *       }
                     *     ]
                     */
                    steps: components["schemas"]["PrebuiltWorkflowStep"][];
                };
            };
        };
        responses: {
            /** @description v2-workflow result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Request metadata (job_id, duration_ms, credit_usage). */
                        metadata: components["schemas"]["V2WorkflowMetadata"];
                        /**
                         * Output
                         * @description Step results keyed by step name, or a caller-defined projection. For ``parse-extract`` with no projection: ``{"parse-extract": {parse, extract, ground}}``.
                         */
                        output: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-workflow_list_jobs": {
        parameters: {
            query?: {
                /** @description Page number (0-indexed). */
                page?: number;
                /** @description Number of items per page. */
                page_size?: number;
                /** @description Filter by job status. */
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's jobs, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        has_more?: boolean;
                        jobs?: {
                            completed_at?: string | null;
                            created_at?: string | null;
                            failure_reason?: string | null;
                            job_id?: string;
                            /** @enum {string} */
                            status?: "pending" | "processing" | "completed" | "failed";
                            version?: string | null;
                        }[];
                        page?: number;
                        page_size?: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    "v2-workflow_create_job": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Inputs
                     * @description Named document sources. Each key is a logical name referenced from steps as ``"$inputs.<name>"``. The gateway stages binary multipart uploads internally before the workflow runs.
                     * @example {
                     *       "report": {
                     *         "document": "report_pdf"
                     *       }
                     *     }
                     */
                    inputs: {
                        [key: string]: components["schemas"]["WorkflowDocumentInput"];
                    };
                    /**
                     * Output
                     * @description Optional projection map. Keys are caller-chosen response field names; values are ``$output.<step>.<field>...`` references. Omitted → full results tree returned under ``output``.
                     * @default null
                     * @example {
                     *       "revenue": "$output.parse-extract.extract.extraction.revenue",
                     *       "revenue_box": "$output.parse-extract.ground.revenue"
                     *     }
                     */
                    output?: {
                        [key: string]: string;
                    } | null;
                    /** @description Async service tier. ``priority`` runs in the fast lane at the sync billing rate; absent → ``standard``. */
                    service_tier?: ("standard" | "priority") | null;
                    /**
                     * Steps
                     * @description Phase 1: a single prebuilt-pipeline step (name must be ``"parse-extract"``). Its result appears in ``output`` under the step's name.
                     * @example [
                     *       {
                     *         "document": "$inputs.report",
                     *         "name": "parse-extract",
                     *         "schema": {
                     *           "properties": {
                     *             "revenue": {
                     *               "type": "string"
                     *             }
                     *           },
                     *           "type": "object"
                     *         }
                     *       }
                     *     ]
                     */
                    steps: components["schemas"]["PrebuiltWorkflowStep"][];
                };
                "multipart/form-data": {
                    /**
                     * Inputs
                     * @description Named document sources. Each key is a logical name referenced from steps as ``"$inputs.<name>"``. The gateway stages binary multipart uploads internally before the workflow runs. JSON-serialized string in form data.
                     * @example {
                     *       "report": {
                     *         "document": "report_pdf"
                     *       }
                     *     }
                     */
                    inputs: {
                        [key: string]: components["schemas"]["WorkflowDocumentInput"];
                    };
                    /**
                     * Output
                     * @description Optional projection map. Keys are caller-chosen response field names; values are ``$output.<step>.<field>...`` references. Omitted → full results tree returned under ``output``. JSON-serialized string in form data.
                     * @default null
                     * @example {
                     *       "revenue": "$output.parse-extract.extract.extraction.revenue",
                     *       "revenue_box": "$output.parse-extract.ground.revenue"
                     *     }
                     */
                    output?: {
                        [key: string]: string;
                    } | null;
                    /** @description Async service tier. ``priority`` runs in the fast lane at the sync billing rate; absent → ``standard``. */
                    service_tier?: ("standard" | "priority") | null;
                    /**
                     * Steps
                     * @description Phase 1: a single prebuilt-pipeline step (name must be ``"parse-extract"``). Its result appears in ``output`` under the step's name. JSON-serialized string in form data.
                     * @example [
                     *       {
                     *         "document": "$inputs.report",
                     *         "name": "parse-extract",
                     *         "schema": {
                     *           "properties": {
                     *             "revenue": {
                     *               "type": "string"
                     *             }
                     *           },
                     *           "type": "object"
                     *         }
                     *       }
                     *     ]
                     */
                    steps: components["schemas"]["PrebuiltWorkflowStep"][];
                };
            };
        };
        responses: {
            /** @description Job created */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created_at?: string | null;
                        job_id?: string;
                        /** @enum {string} */
                        status?: "pending" | "processing" | "completed" | "failed";
                    };
                };
            };
        };
    };
    "v2-workflow_get_job": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier of the job to retrieve, as returned by the create-job request. */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job status / result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Present once the job is terminal. */
                        completed_at?: string;
                        created_at?: string | null;
                        /** @description Present once status is ``failed``. */
                        error?: {
                            /** @description Stable error code (``internal_error`` when unmapped). */
                            code?: string;
                            message?: string;
                        };
                        job_id?: string;
                        /** @description Best-effort progress, present while processing only for jobs that report it. */
                        progress?: unknown;
                        /** @description Present once status is ``completed``. */
                        result?: {
                            /** @description Request metadata (job_id, duration_ms, credit_usage). */
                            metadata: components["schemas"]["V2WorkflowMetadata"];
                            /**
                             * Output
                             * @description Step results keyed by step name, or a caller-defined projection. For ``parse-extract`` with no projection: ``{"parse-extract": {parse, extract, ground}}``.
                             */
                            output: {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @enum {string} */
                        status?: "pending" | "processing" | "completed" | "failed";
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
