name: Release Doctor
on:
  workflow_dispatch:

jobs:
  release_doctor:
    name: release doctor
    runs-on: ubuntu-latest
    if: github.repository == 'landing-ai/ade-typescript'

    steps:
      - uses: actions/checkout@v6

      - name: Check release environment
        run: |
          bash ./bin/check-release-environment

